select
	PRODUCT_GROUP.GROUP_NAME,
	PRODUCT_GROUP.PRODUCTION_TIME as GROUP_PRODUCTION_TIME,
	ACCOUNT_CHARACTER.SKILL_INDUSTRY,
	ACCOUNT_CHARACTER.SKILL_PRODUCTION_EFFICIENCY,
	PRODUCT_BLUEPRINT.ME,
	PRODUCT_BLUEPRINT.PE,
	PRODUCT_TYPE.TYPE_ID as PRODUCT_ID,
	PRODUCT_TYPE.TYPE_NAME as PRODUCT_NAME,
	PRODUCT_TYPE.PORTION_SIZE,
	PRODUCT_PRICE.SELL_MIN,
	MATERIAL_TYPE.TYPE_ID as MATERIAL_ID,
	MATERIAL_TYPE.TYPE_NAME as MATERIAL_NAME,
	MATERIAL_PRICE.BUY_MAX,
	MATERIAL.QUANTITY,
	BLUEPRINT.WASTE_FACTOR,
	BLUEPRINT.PRODUCTION_TIME as PRODUCT_PRODUCTION_TIME,
	BLUEPRINT.PRODUCTIVITY_MODIFIER
from
	MATERIAL
	inner join BLUEPRINT
		on	MATERIAL.TYPE_ID = BLUEPRINT.PRODUCT_TYPE_ID
	inner join PRODUCT_BLUEPRINT
		on	BLUEPRINT.BLUEPRINT_TYPE_ID = PRODUCT_BLUEPRINT.BLUEPRINT_TYPE_ID
	inner join TYPE as PRODUCT_TYPE
		on	MATERIAL.TYPE_ID = PRODUCT_TYPE.TYPE_ID
	inner join TYPE as MATERIAL_TYPE
		on	MATERIAL.MATERIAL_TYPE_ID = MATERIAL_TYPE.TYPE_ID
	inner join PRODUCT_GROUP
		on	PRODUCT_BLUEPRINT.PRODUCT_GROUP = PRODUCT_GROUP.ID
	inner join ACCOUNT_CHARACTER
		on	PRODUCT_GROUP.CHARACTER_ID = ACCOUNT_CHARACTER.CHARACTER_ID
	inner join PRODUCT_PRICE
		on PRODUCT_TYPE.TYPE_ID = PRODUCT_PRICE.TYPE_ID
	inner join PRODUCT_PRICE as MATERIAL_PRICE
		on MATERIAL_TYPE.TYPE_ID = MATERIAL_PRICE.TYPE_ID
order by
	PRODUCT_GROUP.GROUP_NAME,
	PRODUCT_TYPE.TYPE_NAME,
	MATERIAL_TYPE.TYPE_NAME
