select
  TRANSACTION_ID,
  TRANSACTION_DATE_TIME,
  TYPE_ID,
  TYPE_NAME,
  QUANTITY,
  PRICE,
  CLIENT_ID,
  CLIENT_NAME,
  STATION_ID,
  STATION_NAME,
  TRANSACTION_TYPE,
  TRANSACTION_FOR,
  JOURNAL_TRANSACTION_ID,
  ACCOUNT_KEY,
  CHARACTER_ID
from
  WALLET_TRANSACTION
order by
  TRANSACTION_ID desc
